# Generated by Django 3.1 on 2020-09-08 11:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetail',
            fields=[
                ('vendor_detai_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(default='', max_length=50)),
                ('Company_Name', models.CharField(default='', max_length=100)),
                ('Service_decsription', models.TextField(default='', max_length=1000)),
                ('Mobile_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Mobile_No_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(choices=[('1', 'Please Select'), ('2', 'Andra Pradesh'), ('3', 'Arunachal Pradesh'), ('4', 'Assam'), ('5', 'Bihar'), ('6', 'Chhattisgarh'), ('7', 'Chandigarh'), ('8', 'Dadar and Nagar Haveli'), ('9', 'Daman and Diu'), ('10', 'Delhi'), ('11', 'Goa'), ('12', 'Gujarat'), ('13', 'Haryana'), ('14', 'Himachal Pradesh'), ('15', 'Jammu and Kashmir'), ('16', 'Jharkhand'), ('17', 'Karnataka'), ('18', 'Kerala'), ('19', 'Lakshadeep'), ('20', 'Madya Pradesh'), ('21', 'Maharashtra'), ('22', 'Manipur'), ('23', 'Meghalaya'), ('24', 'Mizoram'), ('25', 'Nagaland'), ('26', 'Orissa'), ('27', 'Punjab'), ('28', 'Pondicherry'), ('29', 'Rajasthan'), ('30', 'Sikkim'), ('31', 'Tamil Nadu'), ('32', 'Telagana'), ('33', 'Tripura'), ('34', 'Uttaranchal'), ('35', 'Uttar Pradesh'), ('36', 'West Bengal'), ('37', 'Andaman and Nicobar Island')], default='Please Select', max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Contact_Person', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('EmailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('Landline', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('GST_No', models.IntegerField(blank=True, null=True)),
                ('Pan_No', models.IntegerField(blank=True, null=True)),
                ('TIN_No', models.IntegerField(blank=True, null=True)),
                ('Registered_Trade_Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Facebook_URL', models.URLField(blank=True, null=True)),
                ('Twitter_URL', models.URLField(blank=True, null=True)),
                ('website_URL', models.URLField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('1', 'Please Select'), ('2', 'New'), ('3', 'Verified')], default='New', max_length=20)),
                ('Other_Info', models.CharField(blank=True, max_length=200, null=True)),
                ('Discount_Percentage', models.IntegerField(null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(upload_to='')),
                ('Busniess_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Vendor Details',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('vendor_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendordetail')),
            ],
        ),
    ]
